server:
  port: 8081
  servlet:
    context-path: /template

spring:
  application:
    name: eureka-client-demo-template
  datasource:
    url: jdbc:mysql://39.100.13.171:3306/rui_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Aliyun123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 39.100.13.171
    port: 6379
    password:
    timeout: 300

mybatis:
  mapper-locations: classpath:mapper/*.xml

# -----------------------------------------------------------------------------------------------------

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# -------------------------------------    配置监控端点 ------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: imooc-coupon-template
    groupId: imooc-coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT

# --------------------------------------   log配置    -----------------------------------------------

logging:
  level:
    com.imooc.coupon: debug